//! The `error-page` node — replaces the body and content type of
//! gateway-generated error responses (404, 500, 502, 503) with configured
//! pages. Port of APISIX's `error-page` plugin (response-phase: place after
//! `upstream`, before `client`).
//!
//! Deviations from APISIX:
//! - APISIX configures the pages via plugin *metadata* (with an `enable`
//!   flag); featherbit has no metadata tier, so the pages live directly in
//!   the node config and placing the node in the graph is the enable switch.
//! - APISIX only intercepts responses whose source is not the upstream
//!   (`get_response_source(ctx) ~= "upstream"`). featherbit's equivalent
//!   heuristic is `Context.errors` being non-empty — a response produced by
//!   the gateway (error-handler, auth rejection, ...) always carries the
//!   error record that routed it there, while a clean upstream response does
//!   not. An upstream's own 502 therefore passes through untouched, exactly
//!   as in APISIX.

use async_trait::async_trait;
use bytes::Bytes;
use std::collections::HashMap;

use crate::context::Context;
use crate::plugins::{Plugin, PluginOutput, PluginResult};

/// The status codes APISIX's error-page supports (its metadata schema
/// hardcodes `error_404` / `error_500` / `error_502` / `error_503`).
const SUPPORTED_STATUS: [(u16, &str); 4] = [
    (404, "404 Not Found"),
    (500, "500 Internal Server Error"),
    (502, "502 Bad Gateway"),
    (503, "503 Service Unavailable"),
];

/// One configured error page.
struct ErrorPage {
    body: Bytes,
    content_type: String,
}

/// Replaces `Context.response.body` and `content-type` when the response was
/// generated by the gateway (heuristic: `Context.errors` non-empty) and its
/// status code has a configured page. All other responses pass through
/// unchanged. This plugin never fails at execution time.
pub struct ErrorPagePlugin {
    pages: HashMap<u16, ErrorPage>,
}

/// The default page body, mirroring APISIX's `err_body` template (with the
/// gateway's own name in the footer).
fn default_body(title: &str) -> String {
    format!(
        "<html>\n<head><title>{title}</title></head>\n<body>\n\
         <center><h1>{title}</h1></center>\n\
         <hr><center>featherbit</center>\n</body>\n</html>"
    )
}

impl ErrorPagePlugin {
    /// Builds the plugin from node config.
    ///
    /// Accepted keys (all optional; only the configured statuses are
    /// intercepted): `error_404`, `error_500`, `error_502`, `error_503` —
    /// each an object with:
    /// - `body` (string, default an APISIX-style HTML page for that status):
    ///   the replacement response body.
    /// - `content_type` (string, default `text/html`): the replacement
    ///   `content-type` header value.
    ///
    /// An `error_XXX` key set to a non-object, or `body`/`content_type` with
    /// a non-string value, fails at config load. Setting a key to an empty
    /// object `{}` selects the defaults for that status.
    ///
    /// ```yaml
    /// type: error-page
    /// config:
    ///   error_502:
    ///     body: '{"error": "upstream unavailable"}'
    ///     content_type: application/json
    ///   error_503: {}   # default featherbit HTML page
    /// ```
    pub fn from_config(config: &HashMap<String, serde_json::Value>) -> Result<Self, String> {
        let mut pages = HashMap::new();

        for (status, title) in SUPPORTED_STATUS {
            let key = format!("error_{}", status);
            let Some(raw) = config.get(&key) else {
                continue;
            };
            let obj = raw
                .as_object()
                .ok_or_else(|| format!("{} must be an object", key))?;

            let body = match obj.get("body") {
                None => default_body(title),
                Some(v) => v
                    .as_str()
                    .ok_or_else(|| format!("{}.body must be a string", key))?
                    .to_string(),
            };
            let content_type = match obj.get("content_type") {
                None => "text/html".to_string(),
                Some(v) => v
                    .as_str()
                    .ok_or_else(|| format!("{}.content_type must be a string", key))?
                    .to_string(),
            };

            pages.insert(
                status,
                ErrorPage {
                    body: Bytes::from(body),
                    content_type,
                },
            );
        }

        Ok(Self { pages })
    }
}

#[async_trait]
impl Plugin for ErrorPagePlugin {
    fn plugin_type(&self) -> &str {
        "error-page"
    }

    async fn execute(
        &self,
        mut ctx: Context,
        _named_inputs: &HashMap<String, serde_json::Value>,
    ) -> PluginResult {
        // Only gateway-generated responses are intercepted (APISIX skips
        // responses sourced from the upstream).
        let gateway_generated = !ctx.errors.is_empty();

        if gateway_generated {
            if let Some(page) = self.pages.get(&ctx.response.status_code) {
                ctx.response.body = page.body.clone();
                ctx.response
                    .headers
                    .insert("content-type".to_string(), vec![page.content_type.clone()]);
                // Body-mutation convention: the server layer recomputes the
                // length; the configured page is not encoded.
                ctx.response.headers.remove("content-length");
                ctx.response.headers.remove("content-encoding");
            }
        }

        Ok(PluginOutput {
            context: ctx,
            named_outputs: HashMap::new(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::context::{GatewayError, GatewayRequest, GatewayResponse, Protocol};

    fn test_context(status: u16, gateway_generated: bool) -> Context {
        let mut response_headers = HashMap::new();
        response_headers.insert("content-type".to_string(), vec!["text/plain".to_string()]);
        response_headers.insert("content-length".to_string(), vec!["8".to_string()]);
        let errors = if gateway_generated {
            vec![GatewayError {
                node_id: "upstream-1".to_string(),
                code: "UPSTREAM_CONNECTION_ERROR".to_string(),
                message: "connect refused".to_string(),
                metadata: HashMap::new(),
            }]
        } else {
            Vec::new()
        };
        Context {
            request: GatewayRequest {
                method: "GET".to_string(),
                path: "/test".to_string(),
                host: "localhost".to_string(),
                scheme: "http".to_string(),
                headers: HashMap::new(),
                query_params: HashMap::new(),
                body: Bytes::new(),
                remote_addr: "127.0.0.1:12345".to_string(),
                protocol: Protocol::Http1,
            },
            response: GatewayResponse {
                status_code: status,
                headers: response_headers,
                body: Bytes::from_static(b"original"),
            },
            message: HashMap::new(),
            errors,
        }
    }

    fn plugin(config: serde_json::Value) -> ErrorPagePlugin {
        let map: HashMap<String, serde_json::Value> =
            serde_json::from_value(config).expect("test config must be an object");
        ErrorPagePlugin::from_config(&map).expect("config should be valid")
    }

    #[tokio::test]
    async fn test_error_page_replaces_gateway_error() {
        let p = plugin(serde_json::json!({
            "error_502": {
                "body": "{\"error\": \"bad gateway\"}",
                "content_type": "application/json"
            }
        }));
        let out = p
            .execute(test_context(502, true), &HashMap::new())
            .await
            .unwrap();
        assert_eq!(
            out.context.response.body.as_ref(),
            b"{\"error\": \"bad gateway\"}"
        );
        assert_eq!(
            out.context.response.headers.get("content-type"),
            Some(&vec!["application/json".to_string()])
        );
        assert!(!out.context.response.headers.contains_key("content-length"));
        assert_eq!(out.context.response.status_code, 502);
    }

    #[tokio::test]
    async fn test_error_page_default_body_and_content_type() {
        let p = plugin(serde_json::json!({ "error_503": {} }));
        let out = p
            .execute(test_context(503, true), &HashMap::new())
            .await
            .unwrap();
        let body = String::from_utf8(out.context.response.body.to_vec()).unwrap();
        assert!(body.contains("<h1>503 Service Unavailable</h1>"), "{body}");
        assert!(body.contains("featherbit"));
        assert_eq!(
            out.context.response.headers.get("content-type"),
            Some(&vec!["text/html".to_string()])
        );
    }

    #[tokio::test]
    async fn test_error_page_skips_upstream_sourced_response() {
        // Same 502, but no gateway errors recorded → the response came from
        // the upstream and must pass through untouched.
        let p = plugin(serde_json::json!({ "error_502": {} }));
        let out = p
            .execute(test_context(502, false), &HashMap::new())
            .await
            .unwrap();
        assert_eq!(out.context.response.body.as_ref(), b"original");
        assert_eq!(
            out.context.response.headers.get("content-type"),
            Some(&vec!["text/plain".to_string()])
        );
        assert!(out.context.response.headers.contains_key("content-length"));
    }

    #[tokio::test]
    async fn test_error_page_skips_unconfigured_status() {
        let p = plugin(serde_json::json!({ "error_502": {} }));
        // 500 is a supported status but has no configured page here.
        let out = p
            .execute(test_context(500, true), &HashMap::new())
            .await
            .unwrap();
        assert_eq!(out.context.response.body.as_ref(), b"original");

        // Non-error statuses always pass through.
        let p = plugin(serde_json::json!({ "error_502": {} }));
        let out = p
            .execute(test_context(200, true), &HashMap::new())
            .await
            .unwrap();
        assert_eq!(out.context.response.body.as_ref(), b"original");
    }

    #[test]
    fn test_error_page_config_validation() {
        for bad in [
            serde_json::json!({ "error_502": "not an object" }),
            serde_json::json!({ "error_404": { "body": 42 } }),
            serde_json::json!({ "error_500": { "content_type": [] } }),
        ] {
            let map: HashMap<String, serde_json::Value> = serde_json::from_value(bad).unwrap();
            assert!(ErrorPagePlugin::from_config(&map).is_err());
        }
        // Unsupported error_XXX keys are ignored (only 404/500/502/503 exist
        // in APISIX's schema).
        let map: HashMap<String, serde_json::Value> =
            serde_json::from_value(serde_json::json!({ "error_418": {} })).unwrap();
        let p = ErrorPagePlugin::from_config(&map).unwrap();
        assert!(p.pages.is_empty());
    }
}
