import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['getting-started/intro', 'getting-started/quick-start', 'getting-started/first-route'],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        'concepts/architecture',
        'concepts/policies-and-graphs',
        'concepts/context-object',
        'concepts/listener-and-client',
        'concepts/error-handling',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/configuration',
        'guides/routing',
        'guides/lua-scripting',
        'guides/web-ui',
        'guides/admin-api',
        'guides/observability',
        'guides/debugging',
        'guides/tls',
        'guides/stream',
        'guides/deployment',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'Plugins',
          link: {type: 'doc', id: 'reference/plugins/index'},
          // Grouped into the same categories the plugin index page uses, in the
          // same order — the sidebar and the index are two views of one taxonomy.
          items: [
            {
              type: 'category',
              label: 'Structural & core proxy',
              items: [
                'reference/plugins/listener-client',
                'reference/plugins/upstream',
                'reference/plugins/proxy-rewrite',
                'reference/plugins/response-rewrite',
                'reference/plugins/body-transformer',
                'reference/plugins/degraphql',
                'reference/plugins/redirect',
                'reference/plugins/echo',
                'reference/plugins/gzip',
                'reference/plugins/brotli',
                'reference/plugins/request-id',
                'reference/plugins/real-ip',
              ],
            },
            {
              type: 'category',
              label: 'Error handling & mocking',
              items: [
                'reference/plugins/error-handler',
                'reference/plugins/error-page',
                'reference/plugins/exit-transformer',
                'reference/plugins/mocking',
              ],
            },
            {
              type: 'category',
              label: 'Security & access control',
              items: [
                'reference/plugins/cors',
                'reference/plugins/csrf',
                'reference/plugins/ip-restriction',
                'reference/plugins/ua-restriction',
                'reference/plugins/referer-restriction',
                'reference/plugins/uri-blocker',
                'reference/plugins/request-size-limit',
                'reference/plugins/request-validation',
                'reference/plugins/data-mask',
              ],
            },
            {
              type: 'category',
              label: 'Traffic control',
              items: [
                'reference/plugins/rate-limit',
                'reference/plugins/limit-count',
                'reference/plugins/limit-conn',
                'reference/plugins/api-breaker',
                'reference/plugins/traffic-split',
                'reference/plugins/proxy-mirror',
                'reference/plugins/proxy-cache',
                'reference/plugins/fault-injection',
                'reference/plugins/workflow',
                'reference/plugins/traffic-label',
              ],
            },
            {
              type: 'category',
              label: 'Authentication & consumers',
              items: [
                'reference/plugins/key-auth',
                'reference/plugins/basic-auth',
                'reference/plugins/jwt-auth',
                'reference/plugins/hmac-auth',
                'reference/plugins/jwe-decrypt',
                'reference/plugins/multi-auth',
                'reference/plugins/ldap-auth',
                'reference/plugins/consumer-restriction',
                'reference/plugins/acl',
                'reference/plugins/attach-consumer-label',
              ],
            },
            {
              type: 'category',
              label: 'External auth & authorization',
              items: [
                'reference/plugins/forward-auth',
                'reference/plugins/opa',
                'reference/plugins/authz-casbin',
                'reference/plugins/authz-keycloak',
                'reference/plugins/authz-casdoor',
                'reference/plugins/openid-connect',
                'reference/plugins/cas-auth',
                'reference/plugins/wolf-rbac',
                'reference/plugins/dingtalk-auth',
                'reference/plugins/feishu-auth',
              ],
            },
            {
              type: 'category',
              label: 'Serverless & FaaS',
              items: [
                'reference/plugins/serverless-pre-function',
                'reference/plugins/serverless-post-function',
                'reference/plugins/oas-validator',
                'reference/plugins/aws-lambda',
                'reference/plugins/azure-functions',
                'reference/plugins/openwhisk',
                'reference/plugins/openfunction',
              ],
            },
            {
              type: 'category',
              label: 'Observability & logging',
              items: [
                'reference/plugins/logging',
                'reference/plugins/http-logger',
                'reference/plugins/tcp-logger',
                'reference/plugins/udp-logger',
                'reference/plugins/syslog',
                'reference/plugins/file-logger',
                'reference/plugins/error-log-logger',
                'reference/plugins/elasticsearch-logger',
                'reference/plugins/clickhouse-logger',
                'reference/plugins/loki-logger',
                'reference/plugins/splunk-hec-logging',
                'reference/plugins/datadog',
                'reference/plugins/loggly',
                'reference/plugins/google-cloud-logging',
                'reference/plugins/sls-logger',
                'reference/plugins/tencent-cloud-cls',
                'reference/plugins/skywalking-logger',
                'reference/plugins/lago',
              ],
            },
            {
              type: 'category',
              label: 'Tracing & metrics',
              items: [
                'reference/plugins/prometheus',
                'reference/plugins/opentelemetry',
                'reference/plugins/zipkin',
                'reference/plugins/skywalking',
              ],
            },
            'reference/plugins/script',
          ],
        },
        'reference/roadmap',
      ],
    },
  ],
};

export default sidebars;
